name: test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python -m pytest -v --cov=stack --cov=tests

          python -m pytest -v --cov=stack --cov=tests >> report.md
          cml-send-comment report.md